---
version: 1
update_configs:
  - package_manager: "go:modules"
    directory: "/"
    update_schedule: weekly
    automerged_updates:
      - match:
          dependency_type: production
          update_type: semver:minor
  - package_manager: "docker"
    directory: "/"
    update_schedule: daily
